image: "python:3.7"

before_script:
  - apt-get update -qy
  - apt-get install -y sudo screen
  - pip3 install -r requirements.txt

stages:
  - test

test:
  stage: test
  script:
  - sleep 3
  - cd jooya
  - python3 manage.py test
