# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-16 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='things',
            name='image',
            field=models.ImageField(blank=True, upload_to='things_pic'),
        ),
    ]
