# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-15 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_things_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='things',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
