# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-14 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0003_auto_20190314_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='things',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
    ]
