# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-16 02:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0003_things_name'),
        ('things', '0004_auto_20190314_1237'),
    ]

    operations = [
    ]
