# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-01-24 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0006_remove_things_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='things',
            name='title',
            field=models.CharField(default='title', max_length=1000, verbose_name='عنوان'),
        ),
    ]
