# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-01-24 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0008_auto_20200124_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='things',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
