# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-19 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190319_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='account',
            name='role',
        ),
        migrations.AddField(
            model_name='account',
            name='link',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
